version: 2.1

parameters:
  image-tag:
    type: string
    default: "current"

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17
    working_directory: ~/project

jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install
            echo "âœ… All dependencies installed!"
      - run:
          name: Run Jest tests
          command: npx jest --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/
            JEST_JUNIT_ADD_FILE_ATTRIBUTE: "true"
      - store_test_results:
          path: ./reports/

  testSplit:
    executor: node-executor
    parallelism: 6
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Run Jest tests with splitting
          command: |
            npx jest --listTests \
              | circleci tests run \
                  --command="JEST_JUNIT_ADD_FILE_ATTRIBUTE=true xargs npx jest --ci --runInBand --reporters=default --reporters=jest-junit --" \
                  --verbose \
                  --split-by=timings
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/
      - store_test_results:
          path: ./reports/

  testSmarterTesting:
    executor: node-executor
    parallelism: 6
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Run Jest tests with Smarter Testing
          command: |
            circleci run testsuite "ci tests" --test-selection="all"
      - store_test_results:
          path: ./reports/
      - store_artifacts:
          path: ./reports/
          destination: test-reports

workflows:
  testing:
    jobs:
      - test
      - testSplit
      - testSmarterTesting
